name: Automatic Linting Go Code
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - name: Check out repository code
          uses: actions/checkout@v3
        - name: Setup Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.20.x'
        - name: Lint
          run: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0

            golangci-lint run